name: Deploy Preview Versions

on:
  push:
    branches:
      - test-*
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Copy files
        run: |
         mkdir public
         rsync -av --exclude=public --exclude=.git --exclude=.github ./ public/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ github.ref_name }}